### ISSUE TITLE
Error when importing psk from DBD 

### ISSUE THREAD

**Issue by Mozalthiric** [Befzz/blender3d_import_psk_psa#100]
It says this error: 
Python: Traceback (most recent call last):
  File "C:\Users\model\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2224, in execute
    if not pskimport_proxy():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\model\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2205, in pskimport_proxy
    return pskimport( 
           ^^^^^^^^^^
  File "C:\Users\model\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1051, in pskimport
    mesh_data.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'

**Comment by Archie71boi** [comment]
got the exact same issue

**Comment by Mozalthiric** [comment]
> got the exact same issue

I figured out why. It's because Blender 4.1 or above 3.6 does not support these files, so all you have to do to fix this problem is download Blender 3.6 and reinstall the same add-ons on there and you should be good (Lmk if it works)
