### ISSUE TITLE
'NoneType' object has no attribute 'vec_tail_axis'

### ISSUE THREAD

**Issue by dantman** [Befzz/blender3d_import_psk_psa#5]
I get the following with the no_anim version when used on one specific model.

The model is the Viscera/Gameplay/GP_Tools/SK_GP_Scanner01_3rd skeletal mesh from Viscera Cleanup Detail.

```
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_import_scene_unreal_psa_psk_befzz_no_anim.py", line 1535, in execute
    opts.single_uvtexture
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_import_scene_unreal_psa_psk_befzz_no_anim.py", line 1392, in getInputFilenamepsk
    return pskimport(filename, bImportmesh, bImportbone, bDebugLogPSK, bImportsingleuv)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_import_scene_unreal_psa_psk_befzz_no_anim.py", line 619, in pskimport
    md5_bones, md5_bone, bpy.context.scene.psk_import.bonesize)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_import_scene_unreal_psa_psk_befzz_no_anim.py", line 127, in blen_calc_bone_orient
    return md5_bone.matrix_global * (md5_bone.parent.vec_tail_axis.normalized() * blen_min)
AttributeError: 'NoneType' object has no attribute 'vec_tail_axis'

location: <unknown location>:-1
```

Just thought I should report it. I don't actually care about importing this file, I don't actually need this model, I just encountered the error because I'm batch converting a bunch of models.

One possibly relevant peculiarity of the model I see when importing with the normal befzz version is that the model only has a single bone.

**Comment by Befzz** [comment]
fixed time ago
