### ISSUE TITLE
Unable to import psk

### ISSUE THREAD

**Issue by RenatoMaker** [Befzz/blender3d_import_psk_psa#72]
every time I click to import psk file I get this error message

![Captura de tela 2021-10-10 213325](https://user-images.githubusercontent.com/92279826/136718544-9306b44c-d5ed-4fa7-894b-75fdb1c23627.png)

**Comment by Blenux** [comment]
What psk files are you trying to import?

**Comment by real-guilty** [comment]
Same in 2.9 and 2.93 (Steam). Assets are FF7 Remake exported via Noesis.

Python: Traceback (most recent call last):
  File "C:\Users\JMTB3\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2017, in execute
    no_errors = no_errors and pskimport( 
  File "C:\Users\JMTB3\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 581, in pskimport
    CHUNKS_HANDLERS[chunk_id_str]()
  File "C:\Users\JMTB3\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 407, in read_faces
    ((vertid0, u0, v0, matid0), (vertid1, u1, v1, matid1), (vertid2, u2, v2, matid2)) = Wedges[WdgIdx1], Wedges[WdgIdx2], Wedges[WdgIdx3]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by Befzz** [comment]
@real-guilty hey! 

> exported via Noesis

share psk/psa files! i will look at them!
