### ISSUE TITLE
Blender 2.8 update

### ISSUE THREAD

**Issue by ArchUser87** [Befzz/blender3d_import_psk_psa#9]
Hey Befzz, any chance you can add Blender 2.8 support, get this when trying to import psk in it...

https://imgur.com/wcMFP2U

Thanks, but if no all good....

**Comment by Befzz** [comment]
thx for testing ;)    
2.80 API changes not well documented... need to wait for stability too (crashed many times during test...). 
 
But i've published what i achieved.   

Not well tested and *failing* sometimes.   

Check **latest** branch: https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

**Comment by CastelHQ** [comment]
Hello! The add-on stopped working on the latest builds:

`Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1363, in execute
    opts.bonesize
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1222, in getInputFilenamepsk
    return pskimport(         filename, bImportmesh, bImportbone, bDebugLogPSK, bImportsingleuv, bonesize)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 248, in pskimport
    bpy.ops.outliner.collection_new()
  File "C:\Users\Admin\Desktop\2.8\2.80\scripts\modules\bpy\ops.py", line 192, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.outliner.collection_new.poll() failed, context is incorrect

location: <unknown location>:-1

location: <unknown location>:-1
` 
It's been like that for a week or so.

**Comment by ArchUser87** [comment]
I think Befzz has gone on some strike for reasons unknown, sorry might be a bit of a wait..

**Comment by Befzz** [comment]
pushed to [latest](https://github.com/Befzz/blender3d_import_psk_psa/tree/latest)
