### ISSUE TITLE
I try to import the animation and I have this ??

### ISSUE THREAD

**Issue by captaindan98** [Befzz/blender3d_import_psk_psa#90]
Python: Traceback (most recent call last):
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2312, in execute
    if not psaimport_proxy():
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2293, in psaimport_proxy
    return psaimport(
  File "C:\Users\******\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1879, in psaimport
    strip = nla_stripes.new(action_name, nla_stripes[-1].frame_end, action)
TypeError: NlaStrips.new(): error with argument 2, "start" -  Function.start expected an int type, not float

**Comment by bowlingforsoap** [comment]
This Pull Request seems to solve the exact issue you’ve encountered: https://github.com/Befzz/blender3d_import_psk_psa/pull/85#issue-1229014471
