### ISSUE TITLE
AttributeError with bones?

### ISSUE THREAD

**Issue by Sir-DJ-Cat** [Befzz/blender3d_import_psk_psa#94]
`Python: Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280 (1).py", line 2224, in execute
    if not pskimport_proxy():
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280 (1).py", line 2205, in pskimport_proxy
    return pskimport( 
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280 (1).py", line 1172, in pskimport
    bone_group_unused = armature_obj.pose.bone_groups.new(name = "Unused bones")
AttributeError: 'Pose' object has no attribute 'bone_groups'
`
Getting this error when trying to import a psk model

**Comment by craqvfx** [comment]
getting same issue,havent got a fix yet
Python: Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2224, in execute
    if not pskimport_proxy():
  File "C:\Users\Christian\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2205, in pskimport_proxy
    return pskimport( 
  File "C:\Users\Christian\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1172, in pskimport
    bone_group_unused = armature_obj.pose.bone_groups.new(name = "Unused bones")
AttributeError: 'Pose' object has no attribute 'bone_groups'

**Comment by wisayy** [comment]
I have exactly the same problem
```
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2224, in execute
    if not pskimport_proxy():
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2205, in pskimport_proxy
    return pskimport( 
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1172, in pskimport
    bone_group_unused = armature_obj.pose.bone_groups.new(name = "Unused bones")
AttributeError: 'Pose' object has no attribute 'bone_groups'

```

**Comment by Sir-DJ-Cat** [comment]
Try this one instead, worked fine for me: https://github.com/DarklightGames/io_scene_psk_psa
