### ISSUE TITLE
.pskx models won't import properly

### ISSUE THREAD

**Issue by GuyMcBob** [Befzz/blender3d_import_psk_psa#95]
Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 2164, in execute
    no_errors = no_errors and pskimport(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1226, in pskimport
    bone_group_unused = armature_obj.pose.bone_groups.new(name = "Unused bones")
AttributeError: 'Pose' object has no attribute 'bone_groups'

I already imported one file in an eralier project and it worked flawlessly. In between I activated rigiffy, and fortnite importer. Since this error I have tried removing both, and reinstalling the unreal importer. Does anyone know how to fix this?

**Comment by GuyMcBob** [comment]
Fix found: Blender button > system > Reload Scripts
It still warns of errors but the models appear now
